name: "Terraform Apply"

# Trigger when commits are pushed to the master branch
on:
  push:
    branches:
      - master

jobs:
  terraform-plan:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1.0.1

      # Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform Init"
        run: terraform init -input=false

      # Auto-approve prevents the requirement of human interaction
      - name: "Run - Terraform Apply"
        run: terraform apply -input=false -auto-approve
